{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Mon Feb 10 22:51:59 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",0,0,1000,900);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(0,0,1,1);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_EE = new TH1F("ptPhot_data_EE","ptPhot_data_EE",60,0,300);
   ptPhot_data_EE->SetBinContent(9,5213);
   ptPhot_data_EE->SetBinContent(10,2894);
   ptPhot_data_EE->SetBinContent(11,1688);
   ptPhot_data_EE->SetBinContent(12,1010);
   ptPhot_data_EE->SetBinContent(13,610);
   ptPhot_data_EE->SetBinError(9,72.20111);
   ptPhot_data_EE->SetBinError(10,53.79591);
   ptPhot_data_EE->SetBinError(11,41.08528);
   ptPhot_data_EE->SetBinError(12,31.7805);
   ptPhot_data_EE->SetBinError(13,24.69818);
   ptPhot_data_EE->SetMinimum(0);
   ptPhot_data_EE->SetMaximum(7298.2);
   ptPhot_data_EE->SetEntries(11415);
   ptPhot_data_EE->SetStats(0);
   ptPhot_data_EE->SetMarkerStyle(20);
   ptPhot_data_EE->SetMarkerSize(0.7);
   ptPhot_data_EE->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EE->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EE->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_EE = new TH1F("ptPhot_mc_Bkg_EE","ptPhot_mc_Bkg_EE",60,0,300);
   ptPhot_mc_Bkg_EE->SetBinContent(9,4761.748);
   ptPhot_mc_Bkg_EE->SetBinContent(10,2434.663);
   ptPhot_mc_Bkg_EE->SetBinContent(11,1340.997);
   ptPhot_mc_Bkg_EE->SetBinContent(12,794.9191);
   ptPhot_mc_Bkg_EE->SetBinContent(13,484.0608);
   ptPhot_mc_Bkg_EE->SetBinError(9,44.87974);
   ptPhot_mc_Bkg_EE->SetBinError(10,32.09179);
   ptPhot_mc_Bkg_EE->SetBinError(11,23.60459);
   ptPhot_mc_Bkg_EE->SetBinError(12,17.80514);
   ptPhot_mc_Bkg_EE->SetBinError(13,13.34764);
   ptPhot_mc_Bkg_EE->SetEntries(64068);
   ptPhot_mc_Bkg_EE->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EE->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EE->SetLineColor(ci);
   ptPhot_mc_Bkg_EE->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_EE,"");
   
   TH1F *ptPhot_mc_Signal_EE = new TH1F("ptPhot_mc_Signal_EE","ptPhot_mc_Signal_EE",60,0,300);
   ptPhot_mc_Signal_EE->SetBinContent(9,250.2708);
   ptPhot_mc_Signal_EE->SetBinContent(10,127.6142);
   ptPhot_mc_Signal_EE->SetBinContent(11,58.72121);
   ptPhot_mc_Signal_EE->SetBinContent(12,28.27943);
   ptPhot_mc_Signal_EE->SetBinContent(13,18.49783);
   ptPhot_mc_Signal_EE->SetBinError(9,7.289039);
   ptPhot_mc_Signal_EE->SetBinError(10,5.344873);
   ptPhot_mc_Signal_EE->SetBinError(11,3.439428);
   ptPhot_mc_Signal_EE->SetBinError(12,2.25037);
   ptPhot_mc_Signal_EE->SetBinError(13,2.01721);
   ptPhot_mc_Signal_EE->SetEntries(22476);
   ptPhot_mc_Signal_EE->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EE->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EE->SetLineColor(ci);
   ptPhot_mc_Signal_EE->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_EE,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_EE = new TH1F("ptPhot_data_EE","ptPhot_data_EE",60,0,300);
   ptPhot_data_EE->SetBinContent(9,5213);
   ptPhot_data_EE->SetBinContent(10,2894);
   ptPhot_data_EE->SetBinContent(11,1688);
   ptPhot_data_EE->SetBinContent(12,1010);
   ptPhot_data_EE->SetBinContent(13,610);
   ptPhot_data_EE->SetBinError(9,72.20111);
   ptPhot_data_EE->SetBinError(10,53.79591);
   ptPhot_data_EE->SetBinError(11,41.08528);
   ptPhot_data_EE->SetBinError(12,31.7805);
   ptPhot_data_EE->SetBinError(13,24.69818);
   ptPhot_data_EE->SetMinimum(0);
   ptPhot_data_EE->SetMaximum(7298.2);
   ptPhot_data_EE->SetEntries(11415);
   ptPhot_data_EE->SetStats(0);
   ptPhot_data_EE->SetMarkerStyle(20);
   ptPhot_data_EE->SetMarkerSize(0.7);
   ptPhot_data_EE->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EE->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EE->Draw("PESAME");
   
   TLegend *leg = new TLegend(3.506354e+151,3.680699e+180,5.875218e+232,1.809515e-319,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EE","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_EE","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_EE","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_EE","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
