{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Mon Feb 10 22:52:00 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(-48.75,-901.0124,326.25,8109.111);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_All = new TH1F("ptPhot_data_All","ptPhot_data_All",60,0,300);
   ptPhot_data_All->SetBinContent(9,42017);
   ptPhot_data_All->SetBinContent(10,23557);
   ptPhot_data_All->SetBinContent(11,13836);
   ptPhot_data_All->SetBinContent(12,8519);
   ptPhot_data_All->SetBinContent(13,5393);
   ptPhot_data_All->SetBinError(9,204.9805);
   ptPhot_data_All->SetBinError(10,153.4829);
   ptPhot_data_All->SetBinError(11,117.6265);
   ptPhot_data_All->SetBinError(12,92.29843);
   ptPhot_data_All->SetBinError(13,73.43705);
   ptPhot_data_All->SetMinimum(0);
   ptPhot_data_All->SetMaximum(58823.8);
   ptPhot_data_All->SetEntries(93322);
   ptPhot_data_All->SetStats(0);
   ptPhot_data_All->SetMarkerStyle(20);
   ptPhot_data_All->SetMarkerSize(0.7);
   ptPhot_data_All->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_All->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_All->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_All->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_All = new TH1F("ptPhot_mc_Bkg_All","ptPhot_mc_Bkg_All",60,0,300);
   ptPhot_mc_Bkg_All->SetBinContent(9,30378.91);
   ptPhot_mc_Bkg_All->SetBinContent(10,15937.87);
   ptPhot_mc_Bkg_All->SetBinContent(11,8810.577);
   ptPhot_mc_Bkg_All->SetBinContent(12,5203.964);
   ptPhot_mc_Bkg_All->SetBinContent(13,3136.237);
   ptPhot_mc_Bkg_All->SetBinError(9,113.3444);
   ptPhot_mc_Bkg_All->SetBinError(10,82.08891);
   ptPhot_mc_Bkg_All->SetBinError(11,60.41844);
   ptPhot_mc_Bkg_All->SetBinError(12,45.54101);
   ptPhot_mc_Bkg_All->SetBinError(13,34.01378);
   ptPhot_mc_Bkg_All->SetEntries(509983);
   ptPhot_mc_Bkg_All->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_All->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_All->SetLineColor(ci);
   ptPhot_mc_Bkg_All->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_All,"");
   
   TH1F *ptPhot_mc_Signal_All = new TH1F("ptPhot_mc_Signal_All","ptPhot_mc_Signal_All",60,0,300);
   ptPhot_mc_Signal_All->SetBinContent(9,8973.572);
   ptPhot_mc_Signal_All->SetBinContent(10,5476.752);
   ptPhot_mc_Signal_All->SetBinContent(11,3480.549);
   ptPhot_mc_Signal_All->SetBinContent(12,2265.402);
   ptPhot_mc_Signal_All->SetBinContent(13,1564.874);
   ptPhot_mc_Signal_All->SetBinError(9,38.29843);
   ptPhot_mc_Signal_All->SetBinError(10,27.53689);
   ptPhot_mc_Signal_All->SetBinError(11,20.09984);
   ptPhot_mc_Signal_All->SetBinError(12,14.40479);
   ptPhot_mc_Signal_All->SetBinError(13,11.18106);
   ptPhot_mc_Signal_All->SetEntries(1618110);
   ptPhot_mc_Signal_All->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_All->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_All->SetLineColor(ci);
   ptPhot_mc_Signal_All->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_All,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_All = new TH1F("ptPhot_data_All","ptPhot_data_All",60,0,300);
   ptPhot_data_All->SetBinContent(9,42017);
   ptPhot_data_All->SetBinContent(10,23557);
   ptPhot_data_All->SetBinContent(11,13836);
   ptPhot_data_All->SetBinContent(12,8519);
   ptPhot_data_All->SetBinContent(13,5393);
   ptPhot_data_All->SetBinError(9,204.9805);
   ptPhot_data_All->SetBinError(10,153.4829);
   ptPhot_data_All->SetBinError(11,117.6265);
   ptPhot_data_All->SetBinError(12,92.29843);
   ptPhot_data_All->SetBinError(13,73.43705);
   ptPhot_data_All->SetMinimum(0);
   ptPhot_data_All->SetMaximum(58823.8);
   ptPhot_data_All->SetEntries(93322);
   ptPhot_data_All->SetStats(0);
   ptPhot_data_All->SetMarkerStyle(20);
   ptPhot_data_All->SetMarkerSize(0.7);
   ptPhot_data_All->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_All->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_All->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_All->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.411912e-309,3.237958e-319,2.354764e-310,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","All","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_All","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_All","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_All","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
