{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Mon Feb 10 22:41:12 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(-48.75,-7262.198,326.25,65359.78);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(9,17285);
   ptPhot_data_EB->SetBinContent(10,9229);
   ptPhot_data_EB->SetBinContent(11,5056);
   ptPhot_data_EB->SetBinContent(12,3073);
   ptPhot_data_EB->SetBinContent(13,1913);
   ptPhot_data_EB->SetBinError(9,131.4724);
   ptPhot_data_EB->SetBinError(10,96.06768);
   ptPhot_data_EB->SetBinError(11,71.10556);
   ptPhot_data_EB->SetBinError(12,55.43465);
   ptPhot_data_EB->SetBinError(13,43.73786);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(24199);
   ptPhot_data_EB->SetEntries(36556);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_EB = new TH1F("ptPhot_mc_Bkg_EB","ptPhot_mc_Bkg_EB",60,0,300);
   ptPhot_mc_Bkg_EB->SetBinContent(9,14035.2);
   ptPhot_mc_Bkg_EB->SetBinContent(10,7328.594);
   ptPhot_mc_Bkg_EB->SetBinContent(11,3950.922);
   ptPhot_mc_Bkg_EB->SetBinContent(12,2355.128);
   ptPhot_mc_Bkg_EB->SetBinContent(13,1396.959);
   ptPhot_mc_Bkg_EB->SetBinError(9,76.83781);
   ptPhot_mc_Bkg_EB->SetBinError(10,55.51741);
   ptPhot_mc_Bkg_EB->SetBinError(11,40.28771);
   ptPhot_mc_Bkg_EB->SetBinError(12,30.59065);
   ptPhot_mc_Bkg_EB->SetBinError(13,22.60092);
   ptPhot_mc_Bkg_EB->SetEntries(239915);
   ptPhot_mc_Bkg_EB->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetLineColor(ci);
   ptPhot_mc_Bkg_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_EB,"");
   
   TH1F *ptPhot_mc_Signal_EB = new TH1F("ptPhot_mc_Signal_EB","ptPhot_mc_Signal_EB",60,0,300);
   ptPhot_mc_Signal_EB->SetBinContent(9,2204.863);
   ptPhot_mc_Signal_EB->SetBinContent(10,1274.306);
   ptPhot_mc_Signal_EB->SetBinContent(11,776.3033);
   ptPhot_mc_Signal_EB->SetBinContent(12,474.1165);
   ptPhot_mc_Signal_EB->SetBinContent(13,315.9651);
   ptPhot_mc_Signal_EB->SetBinError(9,19.32507);
   ptPhot_mc_Signal_EB->SetBinError(10,13.42292);
   ptPhot_mc_Signal_EB->SetBinError(11,9.902186);
   ptPhot_mc_Signal_EB->SetBinError(12,6.835915);
   ptPhot_mc_Signal_EB->SetBinError(13,5.174778);
   ptPhot_mc_Signal_EB->SetEntries(369969);
   ptPhot_mc_Signal_EB->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetLineColor(ci);
   ptPhot_mc_Signal_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_EB,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(9,17285);
   ptPhot_data_EB->SetBinContent(10,9229);
   ptPhot_data_EB->SetBinContent(11,5056);
   ptPhot_data_EB->SetBinContent(12,3073);
   ptPhot_data_EB->SetBinContent(13,1913);
   ptPhot_data_EB->SetBinError(9,131.4724);
   ptPhot_data_EB->SetBinError(10,96.06768);
   ptPhot_data_EB->SetBinError(11,71.10556);
   ptPhot_data_EB->SetBinError(12,55.43465);
   ptPhot_data_EB->SetBinError(13,43.73786);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(24199);
   ptPhot_data_EB->SetEntries(36556);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PESAME");
   
   TLegend *leg = new TLegend(0,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EB","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_EB","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_EB","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_EB","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
