{
//=========Macro generated from canvas: mvaIdPhot/mvaIdPhot
//=========  (Mon Feb 10 22:30:29 2014) by ROOT version5.32/00
   TCanvas *mvaIdPhot = new TCanvas("mvaIdPhot", "mvaIdPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   mvaIdPhot->SetHighLightColor(2);
   mvaIdPhot->Range(-1.325,-1393.087,1.175,12537.78);
   mvaIdPhot->SetFillColor(0);
   mvaIdPhot->SetBorderMode(0);
   mvaIdPhot->SetBorderSize(2);
   mvaIdPhot->SetTickx(1);
   mvaIdPhot->SetLeftMargin(0.13);
   mvaIdPhot->SetRightMargin(0.07);
   mvaIdPhot->SetFrameFillStyle(0);
   mvaIdPhot->SetFrameBorderMode(0);
   
   TH1F *mvaIdPhot_data_EB = new TH1F("mvaIdPhot_data_EB","mvaIdPhot_data_EB",100,-1,1);
   mvaIdPhot_data_EB->SetBinContent(96,2355);
   mvaIdPhot_data_EB->SetBinContent(97,4384);
   mvaIdPhot_data_EB->SetBinContent(98,4889);
   mvaIdPhot_data_EB->SetBinContent(99,608);
   mvaIdPhot_data_EB->SetBinContent(100,17);
   mvaIdPhot_data_EB->SetBinError(96,48.52834);
   mvaIdPhot_data_EB->SetBinError(97,66.21178);
   mvaIdPhot_data_EB->SetBinError(98,69.92138);
   mvaIdPhot_data_EB->SetBinError(99,24.65766);
   mvaIdPhot_data_EB->SetBinError(100,4.123106);
   mvaIdPhot_data_EB->SetMinimum(0);
   mvaIdPhot_data_EB->SetMaximum(6844.6);
   mvaIdPhot_data_EB->SetEntries(12253);
   mvaIdPhot_data_EB->SetStats(0);
   mvaIdPhot_data_EB->SetMarkerStyle(20);
   mvaIdPhot_data_EB->SetMarkerSize(0.7);
   mvaIdPhot_data_EB->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EB->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EB->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *mvaIdPhot_mc_Bkg_EB = new TH1F("mvaIdPhot_mc_Bkg_EB","mvaIdPhot_mc_Bkg_EB",100,-1,1);
   mvaIdPhot_mc_Bkg_EB->SetBinContent(96,1074.677);
   mvaIdPhot_mc_Bkg_EB->SetBinContent(97,1648.422);
   mvaIdPhot_mc_Bkg_EB->SetBinContent(98,1485.554);
   mvaIdPhot_mc_Bkg_EB->SetBinContent(99,155.3013);
   mvaIdPhot_mc_Bkg_EB->SetBinContent(100,5.66689);
   mvaIdPhot_mc_Bkg_EB->SetBinError(96,21.09903);
   mvaIdPhot_mc_Bkg_EB->SetBinError(97,26.05681);
   mvaIdPhot_mc_Bkg_EB->SetBinError(98,24.87978);
   mvaIdPhot_mc_Bkg_EB->SetBinError(99,8.187462);
   mvaIdPhot_mc_Bkg_EB->SetBinError(100,1.380719);
   mvaIdPhot_mc_Bkg_EB->SetEntries(60023);
   mvaIdPhot_mc_Bkg_EB->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EB->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EB->SetLineColor(ci);
   mvaIdPhot_mc_Bkg_EB->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Bkg_EB,"");
   
   TH1F *mvaIdPhot_mc_Signal_EB = new TH1F("mvaIdPhot_mc_Signal_EB","mvaIdPhot_mc_Signal_EB",100,-1,1);
   mvaIdPhot_mc_Signal_EB->SetBinContent(96,1167.064);
   mvaIdPhot_mc_Signal_EB->SetBinContent(97,2628.759);
   mvaIdPhot_mc_Signal_EB->SetBinContent(98,3609.453);
   mvaIdPhot_mc_Signal_EB->SetBinContent(99,546.1448);
   mvaIdPhot_mc_Signal_EB->SetBinContent(100,6.817821);
   mvaIdPhot_mc_Signal_EB->SetBinError(96,11.91424);
   mvaIdPhot_mc_Signal_EB->SetBinError(97,18.01555);
   mvaIdPhot_mc_Signal_EB->SetBinError(98,20.94825);
   mvaIdPhot_mc_Signal_EB->SetBinError(99,8.674149);
   mvaIdPhot_mc_Signal_EB->SetBinError(100,0.7744557);
   mvaIdPhot_mc_Signal_EB->SetEntries(635389);
   mvaIdPhot_mc_Signal_EB->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EB->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EB->SetLineColor(ci);
   mvaIdPhot_mc_Signal_EB->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Signal_EB,"");
   ->Draw("hsame");
   
   TH1F *mvaIdPhot_data_EB = new TH1F("mvaIdPhot_data_EB","mvaIdPhot_data_EB",100,-1,1);
   mvaIdPhot_data_EB->SetBinContent(96,2355);
   mvaIdPhot_data_EB->SetBinContent(97,4384);
   mvaIdPhot_data_EB->SetBinContent(98,4889);
   mvaIdPhot_data_EB->SetBinContent(99,608);
   mvaIdPhot_data_EB->SetBinContent(100,17);
   mvaIdPhot_data_EB->SetBinError(96,48.52834);
   mvaIdPhot_data_EB->SetBinError(97,66.21178);
   mvaIdPhot_data_EB->SetBinError(98,69.92138);
   mvaIdPhot_data_EB->SetBinError(99,24.65766);
   mvaIdPhot_data_EB->SetBinError(100,4.123106);
   mvaIdPhot_data_EB->SetMinimum(0);
   mvaIdPhot_data_EB->SetMaximum(6844.6);
   mvaIdPhot_data_EB->SetEntries(12253);
   mvaIdPhot_data_EB->SetStats(0);
   mvaIdPhot_data_EB->SetMarkerStyle(20);
   mvaIdPhot_data_EB->SetMarkerSize(0.7);
   mvaIdPhot_data_EB->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EB->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EB->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.745657e-310,9.068081e-319,6.32404e-322,7.90505e-322,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EB","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("mvaIdPhot_data_EB","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Bkg_EB","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Signal_EB","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   mvaIdPhot->Modified();
   mvaIdPhot->cd();
   mvaIdPhot->SetSelected(mvaIdPhot);
}
