{
//=========Macro generated from canvas: mvaIdPhot/mvaIdPhot
//=========  (Tue Feb 18 12:56:59 2014) by ROOT version5.32/00
   TCanvas *mvaIdPhot = new TCanvas("mvaIdPhot", "mvaIdPhot",0,0,1000,900);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   mvaIdPhot->SetHighLightColor(2);
   mvaIdPhot->Range(0,0,1,1);
   mvaIdPhot->SetFillColor(0);
   mvaIdPhot->SetBorderMode(0);
   mvaIdPhot->SetBorderSize(2);
   mvaIdPhot->SetTickx(1);
   mvaIdPhot->SetLeftMargin(0.13);
   mvaIdPhot->SetRightMargin(0.07);
   mvaIdPhot->SetFrameFillStyle(0);
   mvaIdPhot->SetFrameBorderMode(0);
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(94,3085);
   mvaIdPhot_data_EE->SetBinContent(95,12957);
   mvaIdPhot_data_EE->SetBinContent(96,22090);
   mvaIdPhot_data_EE->SetBinContent(97,37981);
   mvaIdPhot_data_EE->SetBinContent(98,74715);
   mvaIdPhot_data_EE->SetBinContent(99,74068);
   mvaIdPhot_data_EE->SetBinContent(100,7039);
   mvaIdPhot_data_EE->SetBinError(94,55.54278);
   mvaIdPhot_data_EE->SetBinError(95,113.8288);
   mvaIdPhot_data_EE->SetBinError(96,148.6271);
   mvaIdPhot_data_EE->SetBinError(97,194.8871);
   mvaIdPhot_data_EE->SetBinError(98,273.3404);
   mvaIdPhot_data_EE->SetBinError(99,272.1544);
   mvaIdPhot_data_EE->SetBinError(100,83.89875);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(104601);
   mvaIdPhot_data_EE->SetEntries(231935);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *mvaIdPhot_mc_Bkg_EE = new TH1F("mvaIdPhot_mc_Bkg_EE","mvaIdPhot_mc_Bkg_EE",100,-1,1);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(94,1173.016);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(95,5188.243);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(96,6738.556);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(97,8370.295);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(98,8284.717);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(99,4682.43);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(100,164.2911);
   mvaIdPhot_mc_Bkg_EE->SetBinError(94,56.2912);
   mvaIdPhot_mc_Bkg_EE->SetBinError(95,278.5078);
   mvaIdPhot_mc_Bkg_EE->SetBinError(96,299.8415);
   mvaIdPhot_mc_Bkg_EE->SetBinError(97,393.0053);
   mvaIdPhot_mc_Bkg_EE->SetBinError(98,387.0705);
   mvaIdPhot_mc_Bkg_EE->SetBinError(99,241.6746);
   mvaIdPhot_mc_Bkg_EE->SetBinError(100,18.07931);
   mvaIdPhot_mc_Bkg_EE->SetEntries(35158);
   mvaIdPhot_mc_Bkg_EE->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetLineColor(ci);
   mvaIdPhot_mc_Bkg_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Bkg_EE,"");
   
   TH1F *mvaIdPhot_mc_Signal_EE = new TH1F("mvaIdPhot_mc_Signal_EE","mvaIdPhot_mc_Signal_EE",100,-1,1);
   mvaIdPhot_mc_Signal_EE->SetBinContent(94,740.2529);
   mvaIdPhot_mc_Signal_EE->SetBinContent(95,4397.475);
   mvaIdPhot_mc_Signal_EE->SetBinContent(96,9124.844);
   mvaIdPhot_mc_Signal_EE->SetBinContent(97,20372.83);
   mvaIdPhot_mc_Signal_EE->SetBinContent(98,46333.29);
   mvaIdPhot_mc_Signal_EE->SetBinContent(99,65826.69);
   mvaIdPhot_mc_Signal_EE->SetBinContent(100,4631.434);
   mvaIdPhot_mc_Signal_EE->SetBinError(94,25.84343);
   mvaIdPhot_mc_Signal_EE->SetBinError(95,213.5334);
   mvaIdPhot_mc_Signal_EE->SetBinError(96,87.25798);
   mvaIdPhot_mc_Signal_EE->SetBinError(97,254.1216);
   mvaIdPhot_mc_Signal_EE->SetBinError(98,374.4407);
   mvaIdPhot_mc_Signal_EE->SetBinError(99,434.7638);
   mvaIdPhot_mc_Signal_EE->SetBinError(100,91.92288);
   mvaIdPhot_mc_Signal_EE->SetEntries(640592);
   mvaIdPhot_mc_Signal_EE->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetLineColor(ci);
   mvaIdPhot_mc_Signal_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Signal_EE,"");
   ->Draw("hsame");
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(94,3085);
   mvaIdPhot_data_EE->SetBinContent(95,12957);
   mvaIdPhot_data_EE->SetBinContent(96,22090);
   mvaIdPhot_data_EE->SetBinContent(97,37981);
   mvaIdPhot_data_EE->SetBinContent(98,74715);
   mvaIdPhot_data_EE->SetBinContent(99,74068);
   mvaIdPhot_data_EE->SetBinContent(100,7039);
   mvaIdPhot_data_EE->SetBinError(94,55.54278);
   mvaIdPhot_data_EE->SetBinError(95,113.8288);
   mvaIdPhot_data_EE->SetBinError(96,148.6271);
   mvaIdPhot_data_EE->SetBinError(97,194.8871);
   mvaIdPhot_data_EE->SetBinError(98,273.3404);
   mvaIdPhot_data_EE->SetBinError(99,272.1544);
   mvaIdPhot_data_EE->SetBinError(100,83.89875);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(104601);
   mvaIdPhot_data_EE->SetEntries(231935);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.528496e-315,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EE","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("mvaIdPhot_data_EE","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Bkg_EE","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Signal_EE","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   mvaIdPhot->Modified();
   mvaIdPhot->cd();
   mvaIdPhot->SetSelected(mvaIdPhot);
}
