{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Mon Feb 10 21:50:31 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(-48.75,-1552.272,326.25,13970.44);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_All = new TH1F("ptPhot_data_All","ptPhot_data_All",60,0,300);
   ptPhot_data_All->SetBinContent(14,27726);
   ptPhot_data_All->SetBinContent(15,19149);
   ptPhot_data_All->SetBinContent(16,13476);
   ptPhot_data_All->SetBinContent(17,9520);
   ptPhot_data_All->SetBinContent(18,6821);
   ptPhot_data_All->SetBinError(14,166.5113);
   ptPhot_data_All->SetBinError(15,138.3799);
   ptPhot_data_All->SetBinError(16,116.0862);
   ptPhot_data_All->SetBinError(17,97.57049);
   ptPhot_data_All->SetBinError(18,82.58935);
   ptPhot_data_All->SetMinimum(0);
   ptPhot_data_All->SetMaximum(38816.4);
   ptPhot_data_All->SetEntries(76692);
   ptPhot_data_All->SetStats(0);
   ptPhot_data_All->SetMarkerStyle(20);
   ptPhot_data_All->SetMarkerSize(0.7);
   ptPhot_data_All->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_All->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_All->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_All->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_All = new TH1F("ptPhot_mc_Bkg_All","ptPhot_mc_Bkg_All",60,0,300);
   ptPhot_mc_Bkg_All->SetBinContent(14,15152.24);
   ptPhot_mc_Bkg_All->SetBinContent(15,9924.49);
   ptPhot_mc_Bkg_All->SetBinContent(16,6779.778);
   ptPhot_mc_Bkg_All->SetBinContent(17,4396.031);
   ptPhot_mc_Bkg_All->SetBinContent(18,3160.643);
   ptPhot_mc_Bkg_All->SetBinError(14,194.735);
   ptPhot_mc_Bkg_All->SetBinError(15,142.2798);
   ptPhot_mc_Bkg_All->SetBinError(16,104.9364);
   ptPhot_mc_Bkg_All->SetBinError(17,71.68748);
   ptPhot_mc_Bkg_All->SetBinError(18,54.28437);
   ptPhot_mc_Bkg_All->SetEntries(232646);
   ptPhot_mc_Bkg_All->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_All->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_All->SetLineColor(ci);
   ptPhot_mc_Bkg_All->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_All,"");
   
   TH1F *ptPhot_mc_Signal_All = new TH1F("ptPhot_mc_Signal_All","ptPhot_mc_Signal_All",60,0,300);
   ptPhot_mc_Signal_All->SetBinContent(14,8663.518);
   ptPhot_mc_Signal_All->SetBinContent(15,6194.25);
   ptPhot_mc_Signal_All->SetBinContent(16,4548.855);
   ptPhot_mc_Signal_All->SetBinContent(17,3360.638);
   ptPhot_mc_Signal_All->SetBinContent(18,2589.687);
   ptPhot_mc_Signal_All->SetBinError(14,68.69912);
   ptPhot_mc_Signal_All->SetBinError(15,51.02819);
   ptPhot_mc_Signal_All->SetBinError(16,39.22888);
   ptPhot_mc_Signal_All->SetBinError(17,28.31106);
   ptPhot_mc_Signal_All->SetBinError(18,22.54698);
   ptPhot_mc_Signal_All->SetEntries(1082294);
   ptPhot_mc_Signal_All->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_All->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_All->SetLineColor(ci);
   ptPhot_mc_Signal_All->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_All,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_All = new TH1F("ptPhot_data_All","ptPhot_data_All",60,0,300);
   ptPhot_data_All->SetBinContent(14,27726);
   ptPhot_data_All->SetBinContent(15,19149);
   ptPhot_data_All->SetBinContent(16,13476);
   ptPhot_data_All->SetBinContent(17,9520);
   ptPhot_data_All->SetBinContent(18,6821);
   ptPhot_data_All->SetBinError(14,166.5113);
   ptPhot_data_All->SetBinError(15,138.3799);
   ptPhot_data_All->SetBinError(16,116.0862);
   ptPhot_data_All->SetBinError(17,97.57049);
   ptPhot_data_All->SetBinError(18,82.58935);
   ptPhot_data_All->SetMinimum(0);
   ptPhot_data_All->SetMaximum(38816.4);
   ptPhot_data_All->SetEntries(76692);
   ptPhot_data_All->SetStats(0);
   ptPhot_data_All->SetMarkerStyle(20);
   ptPhot_data_All->SetMarkerSize(0.7);
   ptPhot_data_All->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_All->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_All->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_All->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.411912e-309,3.237958e-319,2.323969e-310,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","All","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_All","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_All","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_All","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
