{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Mon Feb 10 21:50:32 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(-48.75,-4792.149,326.25,43129.33);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(14,9652);
   ptPhot_data_EB->SetBinContent(15,6319);
   ptPhot_data_EB->SetBinContent(16,4449);
   ptPhot_data_EB->SetBinContent(17,3033);
   ptPhot_data_EB->SetBinContent(18,2088);
   ptPhot_data_EB->SetBinError(14,98.24459);
   ptPhot_data_EB->SetBinError(15,79.49214);
   ptPhot_data_EB->SetBinError(16,66.70082);
   ptPhot_data_EB->SetBinError(17,55.07268);
   ptPhot_data_EB->SetBinError(18,45.69464);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(13512.8);
   ptPhot_data_EB->SetEntries(25541);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_EB = new TH1F("ptPhot_mc_Bkg_EB","ptPhot_mc_Bkg_EB",60,0,300);
   ptPhot_mc_Bkg_EB->SetBinContent(14,6692.471);
   ptPhot_mc_Bkg_EB->SetBinContent(15,4439.491);
   ptPhot_mc_Bkg_EB->SetBinContent(16,2997.423);
   ptPhot_mc_Bkg_EB->SetBinContent(17,1867.318);
   ptPhot_mc_Bkg_EB->SetBinContent(18,1351.308);
   ptPhot_mc_Bkg_EB->SetBinError(14,129.1104);
   ptPhot_mc_Bkg_EB->SetBinError(15,95.29268);
   ptPhot_mc_Bkg_EB->SetBinError(16,70.05719);
   ptPhot_mc_Bkg_EB->SetBinError(17,46.16859);
   ptPhot_mc_Bkg_EB->SetBinError(18,35.25483);
   ptPhot_mc_Bkg_EB->SetEntries(98214);
   ptPhot_mc_Bkg_EB->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetLineColor(ci);
   ptPhot_mc_Bkg_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_EB,"");
   
   TH1F *ptPhot_mc_Signal_EB = new TH1F("ptPhot_mc_Signal_EB","ptPhot_mc_Signal_EB",60,0,300);
   ptPhot_mc_Signal_EB->SetBinContent(14,1637.363);
   ptPhot_mc_Signal_EB->SetBinContent(15,1154.456);
   ptPhot_mc_Signal_EB->SetBinContent(16,804.7274);
   ptPhot_mc_Signal_EB->SetBinContent(17,582.5419);
   ptPhot_mc_Signal_EB->SetBinContent(18,438.3555);
   ptPhot_mc_Signal_EB->SetBinError(14,28.81206);
   ptPhot_mc_Signal_EB->SetBinError(15,22.00392);
   ptPhot_mc_Signal_EB->SetBinError(16,15.53753);
   ptPhot_mc_Signal_EB->SetBinError(17,10.41533);
   ptPhot_mc_Signal_EB->SetBinError(18,8.883867);
   ptPhot_mc_Signal_EB->SetEntries(201564);
   ptPhot_mc_Signal_EB->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetLineColor(ci);
   ptPhot_mc_Signal_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_EB,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(14,9652);
   ptPhot_data_EB->SetBinContent(15,6319);
   ptPhot_data_EB->SetBinContent(16,4449);
   ptPhot_data_EB->SetBinContent(17,3033);
   ptPhot_data_EB->SetBinContent(18,2088);
   ptPhot_data_EB->SetBinError(14,98.24459);
   ptPhot_data_EB->SetBinError(15,79.49214);
   ptPhot_data_EB->SetBinError(16,66.70082);
   ptPhot_data_EB->SetBinError(17,55.07268);
   ptPhot_data_EB->SetBinError(18,45.69464);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(13512.8);
   ptPhot_data_EB->SetEntries(25541);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.411912e-309,3.237958e-319,2.323969e-310,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EB","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_EB","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_EB","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_EB","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
