{
//=========Macro generated from canvas: mvaIdPhot/mvaIdPhot
//=========  (Tue Feb 18 12:58:57 2014) by ROOT version5.32/00
   TCanvas *mvaIdPhot = new TCanvas("mvaIdPhot", "mvaIdPhot",0,0,1000,900);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   mvaIdPhot->SetHighLightColor(2);
   mvaIdPhot->Range(0,0,1,1);
   mvaIdPhot->SetFillColor(0);
   mvaIdPhot->SetBorderMode(0);
   mvaIdPhot->SetBorderSize(2);
   mvaIdPhot->SetTickx(1);
   mvaIdPhot->SetLeftMargin(0.13);
   mvaIdPhot->SetRightMargin(0.07);
   mvaIdPhot->SetFrameFillStyle(0);
   mvaIdPhot->SetFrameBorderMode(0);
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(94,585);
   mvaIdPhot_data_EE->SetBinContent(95,2504);
   mvaIdPhot_data_EE->SetBinContent(96,3695);
   mvaIdPhot_data_EE->SetBinContent(97,5640);
   mvaIdPhot_data_EE->SetBinContent(98,9664);
   mvaIdPhot_data_EE->SetBinContent(99,9138);
   mvaIdPhot_data_EE->SetBinContent(100,916);
   mvaIdPhot_data_EE->SetBinError(94,24.18677);
   mvaIdPhot_data_EE->SetBinError(95,50.03998);
   mvaIdPhot_data_EE->SetBinError(96,60.78651);
   mvaIdPhot_data_EE->SetBinError(97,75.09993);
   mvaIdPhot_data_EE->SetBinError(98,98.30565);
   mvaIdPhot_data_EE->SetBinError(99,95.59289);
   mvaIdPhot_data_EE->SetBinError(100,30.26549);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(13529.6);
   mvaIdPhot_data_EE->SetEntries(32142);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *mvaIdPhot_mc_Bkg_EE = new TH1F("mvaIdPhot_mc_Bkg_EE","mvaIdPhot_mc_Bkg_EE",100,-1,1);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(94,350.3463);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(95,1330.366);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(96,1563.047);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(97,1837.168);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(98,1719.293);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(99,849.3929);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(100,30.16145);
   mvaIdPhot_mc_Bkg_EE->SetBinError(94,23.31211);
   mvaIdPhot_mc_Bkg_EE->SetBinError(95,77.00963);
   mvaIdPhot_mc_Bkg_EE->SetBinError(96,49.13401);
   mvaIdPhot_mc_Bkg_EE->SetBinError(97,106.1878);
   mvaIdPhot_mc_Bkg_EE->SetBinError(98,75.48802);
   mvaIdPhot_mc_Bkg_EE->SetBinError(99,34.56487);
   mvaIdPhot_mc_Bkg_EE->SetBinError(100,5.8564);
   mvaIdPhot_mc_Bkg_EE->SetEntries(28852);
   mvaIdPhot_mc_Bkg_EE->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetLineColor(ci);
   mvaIdPhot_mc_Bkg_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Bkg_EE,"");
   
   TH1F *mvaIdPhot_mc_Signal_EE = new TH1F("mvaIdPhot_mc_Signal_EE","mvaIdPhot_mc_Signal_EE",100,-1,1);
   mvaIdPhot_mc_Signal_EE->SetBinContent(94,185.4794);
   mvaIdPhot_mc_Signal_EE->SetBinContent(95,906.8522);
   mvaIdPhot_mc_Signal_EE->SetBinContent(96,1711.535);
   mvaIdPhot_mc_Signal_EE->SetBinContent(97,3206.882);
   mvaIdPhot_mc_Signal_EE->SetBinContent(98,6322.228);
   mvaIdPhot_mc_Signal_EE->SetBinContent(99,7894.396);
   mvaIdPhot_mc_Signal_EE->SetBinContent(100,589.0809);
   mvaIdPhot_mc_Signal_EE->SetBinError(94,8.123635);
   mvaIdPhot_mc_Signal_EE->SetBinError(95,17.65752);
   mvaIdPhot_mc_Signal_EE->SetBinError(96,23.71316);
   mvaIdPhot_mc_Signal_EE->SetBinError(97,52.81172);
   mvaIdPhot_mc_Signal_EE->SetBinError(98,55.5828);
   mvaIdPhot_mc_Signal_EE->SetBinError(99,67.85589);
   mvaIdPhot_mc_Signal_EE->SetBinError(100,10.7886);
   mvaIdPhot_mc_Signal_EE->SetEntries(564048);
   mvaIdPhot_mc_Signal_EE->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetLineColor(ci);
   mvaIdPhot_mc_Signal_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Signal_EE,"");
   ->Draw("hsame");
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(94,585);
   mvaIdPhot_data_EE->SetBinContent(95,2504);
   mvaIdPhot_data_EE->SetBinContent(96,3695);
   mvaIdPhot_data_EE->SetBinContent(97,5640);
   mvaIdPhot_data_EE->SetBinContent(98,9664);
   mvaIdPhot_data_EE->SetBinContent(99,9138);
   mvaIdPhot_data_EE->SetBinContent(100,916);
   mvaIdPhot_data_EE->SetBinError(94,24.18677);
   mvaIdPhot_data_EE->SetBinError(95,50.03998);
   mvaIdPhot_data_EE->SetBinError(96,60.78651);
   mvaIdPhot_data_EE->SetBinError(97,75.09993);
   mvaIdPhot_data_EE->SetBinError(98,98.30565);
   mvaIdPhot_data_EE->SetBinError(99,95.59289);
   mvaIdPhot_data_EE->SetBinError(100,30.26549);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(13529.6);
   mvaIdPhot_data_EE->SetEntries(32142);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.096732e-315,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EE","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("mvaIdPhot_data_EE","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Bkg_EE","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Signal_EE","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   mvaIdPhot->Modified();
   mvaIdPhot->cd();
   mvaIdPhot->SetSelected(mvaIdPhot);
}
