{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Fri Jan 31 17:18:38 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(-48.75,-1463.951,326.25,13175.56);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_All = new TH1F("ptPhot_data_All","ptPhot_data_All",60,0,300);
   ptPhot_data_All->SetBinContent(9,42017);
   ptPhot_data_All->SetBinContent(10,23557);
   ptPhot_data_All->SetBinContent(11,13836);
   ptPhot_data_All->SetBinContent(12,8519);
   ptPhot_data_All->SetBinContent(13,5393);
   ptPhot_data_All->SetBinError(9,204.9805);
   ptPhot_data_All->SetBinError(10,153.4829);
   ptPhot_data_All->SetBinError(11,117.6265);
   ptPhot_data_All->SetBinError(12,92.29843);
   ptPhot_data_All->SetBinError(13,73.43705);
   ptPhot_data_All->SetMinimum(0);
   ptPhot_data_All->SetMaximum(58823.8);
   ptPhot_data_All->SetEntries(93322);
   ptPhot_data_All->SetStats(0);
   ptPhot_data_All->SetMarkerStyle(20);
   ptPhot_data_All->SetMarkerSize(0.7);
   ptPhot_data_All->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_All->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_All->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_All->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_All = new TH1F("ptPhot_mc_Bkg_All","ptPhot_mc_Bkg_All",60,0,300);
   ptPhot_mc_Bkg_All->SetBinContent(9,29886.3);
   ptPhot_mc_Bkg_All->SetBinContent(10,15628.09);
   ptPhot_mc_Bkg_All->SetBinContent(11,8619.907);
   ptPhot_mc_Bkg_All->SetBinContent(12,5078.559);
   ptPhot_mc_Bkg_All->SetBinContent(13,3050.449);
   ptPhot_mc_Bkg_All->SetBinError(9,112.5773);
   ptPhot_mc_Bkg_All->SetBinError(10,81.46117);
   ptPhot_mc_Bkg_All->SetBinError(11,59.93774);
   ptPhot_mc_Bkg_All->SetBinError(12,45.16408);
   ptPhot_mc_Bkg_All->SetBinError(13,33.69772);
   ptPhot_mc_Bkg_All->SetEntries(456767);
   ptPhot_mc_Bkg_All->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_All->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_All->SetLineColor(ci);
   ptPhot_mc_Bkg_All->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_All,"");
   
   TH1F *ptPhot_mc_Signal_All = new TH1F("ptPhot_mc_Signal_All","ptPhot_mc_Signal_All",60,0,300);
   ptPhot_mc_Signal_All->SetBinContent(9,9466.304);
   ptPhot_mc_Signal_All->SetBinContent(10,5786.486);
   ptPhot_mc_Signal_All->SetBinContent(11,3671.244);
   ptPhot_mc_Signal_All->SetBinContent(12,2390.851);
   ptPhot_mc_Signal_All->SetBinContent(13,1650.726);
   ptPhot_mc_Signal_All->SetBinError(9,40.49785);
   ptPhot_mc_Signal_All->SetBinError(10,29.34189);
   ptPhot_mc_Signal_All->SetBinError(11,21.49089);
   ptPhot_mc_Signal_All->SetBinError(12,15.54629);
   ptPhot_mc_Signal_All->SetBinError(13,12.10029);
   ptPhot_mc_Signal_All->SetEntries(1671326);
   ptPhot_mc_Signal_All->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_All->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_All->SetLineColor(ci);
   ptPhot_mc_Signal_All->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_All,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_All = new TH1F("ptPhot_data_All","ptPhot_data_All",60,0,300);
   ptPhot_data_All->SetBinContent(9,42017);
   ptPhot_data_All->SetBinContent(10,23557);
   ptPhot_data_All->SetBinContent(11,13836);
   ptPhot_data_All->SetBinContent(12,8519);
   ptPhot_data_All->SetBinContent(13,5393);
   ptPhot_data_All->SetBinError(9,204.9805);
   ptPhot_data_All->SetBinError(10,153.4829);
   ptPhot_data_All->SetBinError(11,117.6265);
   ptPhot_data_All->SetBinError(12,92.29843);
   ptPhot_data_All->SetBinError(13,73.43705);
   ptPhot_data_All->SetMinimum(0);
   ptPhot_data_All->SetMaximum(58823.8);
   ptPhot_data_All->SetEntries(93322);
   ptPhot_data_All->SetStats(0);
   ptPhot_data_All->SetMarkerStyle(20);
   ptPhot_data_All->SetMarkerSize(0.7);
   ptPhot_data_All->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_All->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_All->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_All->Draw("PESAME");
   
   TLegend *leg = new TLegend(0,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","All","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_All","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_All","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_All","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
