{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Fri Jan 31 17:18:40 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(-48.75,-7262.198,326.25,65359.78);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(9,9507);
   ptPhot_data_EB->SetBinContent(10,5487);
   ptPhot_data_EB->SetBinContent(11,3443);
   ptPhot_data_EB->SetBinContent(12,2168);
   ptPhot_data_EB->SetBinContent(13,1492);
   ptPhot_data_EB->SetBinError(9,97.50385);
   ptPhot_data_EB->SetBinError(10,74.07429);
   ptPhot_data_EB->SetBinError(11,58.67708);
   ptPhot_data_EB->SetBinError(12,46.56179);
   ptPhot_data_EB->SetBinError(13,38.62642);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(13309.8);
   ptPhot_data_EB->SetEntries(22097);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_EB = new TH1F("ptPhot_mc_Bkg_EB","ptPhot_mc_Bkg_EB",60,0,300);
   ptPhot_mc_Bkg_EB->SetBinContent(9,4642.277);
   ptPhot_mc_Bkg_EB->SetBinContent(10,2507.317);
   ptPhot_mc_Bkg_EB->SetBinContent(11,1377.776);
   ptPhot_mc_Bkg_EB->SetBinContent(12,841.2535);
   ptPhot_mc_Bkg_EB->SetBinContent(13,508.4496);
   ptPhot_mc_Bkg_EB->SetBinError(9,44.39619);
   ptPhot_mc_Bkg_EB->SetBinError(10,32.67656);
   ptPhot_mc_Bkg_EB->SetBinError(11,24.02939);
   ptPhot_mc_Bkg_EB->SetBinError(12,18.54227);
   ptPhot_mc_Bkg_EB->SetBinError(13,13.93808);
   ptPhot_mc_Bkg_EB->SetEntries(88806);
   ptPhot_mc_Bkg_EB->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetLineColor(ci);
   ptPhot_mc_Bkg_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_EB,"");
   
   TH1F *ptPhot_mc_Signal_EB = new TH1F("ptPhot_mc_Signal_EB","ptPhot_mc_Signal_EB",60,0,300);
   ptPhot_mc_Signal_EB->SetBinContent(9,4792.236);
   ptPhot_mc_Signal_EB->SetBinContent(10,3029.306);
   ptPhot_mc_Signal_EB->SetBinContent(11,1964.783);
   ptPhot_mc_Signal_EB->SetBinContent(12,1294.887);
   ptPhot_mc_Signal_EB->SetBinContent(13,899.5659);
   ptPhot_mc_Signal_EB->SetBinError(9,27.48595);
   ptPhot_mc_Signal_EB->SetBinError(10,20.25702);
   ptPhot_mc_Signal_EB->SetBinError(11,14.94975);
   ptPhot_mc_Signal_EB->SetBinError(12,10.76034);
   ptPhot_mc_Signal_EB->SetBinError(13,8.343675);
   ptPhot_mc_Signal_EB->SetEntries(939838);
   ptPhot_mc_Signal_EB->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetLineColor(ci);
   ptPhot_mc_Signal_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_EB,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(9,9507);
   ptPhot_data_EB->SetBinContent(10,5487);
   ptPhot_data_EB->SetBinContent(11,3443);
   ptPhot_data_EB->SetBinContent(12,2168);
   ptPhot_data_EB->SetBinContent(13,1492);
   ptPhot_data_EB->SetBinError(9,97.50385);
   ptPhot_data_EB->SetBinError(10,74.07429);
   ptPhot_data_EB->SetBinError(11,58.67708);
   ptPhot_data_EB->SetBinError(12,46.56179);
   ptPhot_data_EB->SetBinError(13,38.62642);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(13309.8);
   ptPhot_data_EB->SetEntries(22097);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.411912e-309,3.237958e-319,2.34273e-310,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EB","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_EB","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_EB","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_EB","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
