/********************************************************************
* /afs/cern.ch/work/g/gdimperi/GammaJet/giulia_repo/CMSSW_5_3_14/src/GammaJets/src/fit_clean/Pull/fitData_myPull_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/cern.ch/work/g/gdimperi/GammaJet/giulia_repo/CMSSW_5_3_14/src/GammaJets/src/fit_clean/Pull/fitData_myPull_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablefitData_myPull_C_ACLiC_dict();
extern void G__cpp_setup_inheritancefitData_myPull_C_ACLiC_dict();
extern void G__cpp_setup_typetablefitData_myPull_C_ACLiC_dict();
extern void G__cpp_setup_memvarfitData_myPull_C_ACLiC_dict();
extern void G__cpp_setup_globalfitData_myPull_C_ACLiC_dict();
extern void G__cpp_setup_memfuncfitData_myPull_C_ACLiC_dict();
extern void G__cpp_setup_funcfitData_myPull_C_ACLiC_dict();
extern void G__set_cpp_environmentfitData_myPull_C_ACLiC_dict();
}


#include "/tmp/rootcint_ZsF8RB.h"
