{
//=========Macro generated from canvas: mvaIdPhot/mvaIdPhot
//=========  (Thu Feb  6 16:01:00 2014) by ROOT version5.32/00
   TCanvas *mvaIdPhot = new TCanvas("mvaIdPhot", "mvaIdPhot",0,0,1000,900);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   mvaIdPhot->SetHighLightColor(2);
   mvaIdPhot->Range(0,0,1,1);
   mvaIdPhot->SetFillColor(0);
   mvaIdPhot->SetBorderMode(0);
   mvaIdPhot->SetBorderSize(2);
   mvaIdPhot->SetTickx(1);
   mvaIdPhot->SetLeftMargin(0.13);
   mvaIdPhot->SetRightMargin(0.07);
   mvaIdPhot->SetFrameFillStyle(0);
   mvaIdPhot->SetFrameBorderMode(0);
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(88,217);
   mvaIdPhot_data_EE->SetBinContent(89,608);
   mvaIdPhot_data_EE->SetBinContent(90,640);
   mvaIdPhot_data_EE->SetBinContent(91,769);
   mvaIdPhot_data_EE->SetBinContent(92,889);
   mvaIdPhot_data_EE->SetBinContent(93,1030);
   mvaIdPhot_data_EE->SetBinContent(94,1191);
   mvaIdPhot_data_EE->SetBinContent(95,872);
   mvaIdPhot_data_EE->SetBinError(88,14.73092);
   mvaIdPhot_data_EE->SetBinError(89,24.65766);
   mvaIdPhot_data_EE->SetBinError(90,25.29822);
   mvaIdPhot_data_EE->SetBinError(91,27.73085);
   mvaIdPhot_data_EE->SetBinError(92,29.8161);
   mvaIdPhot_data_EE->SetBinError(93,32.09361);
   mvaIdPhot_data_EE->SetBinError(94,34.51087);
   mvaIdPhot_data_EE->SetBinError(95,29.52965);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(1667.4);
   mvaIdPhot_data_EE->SetEntries(6216);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *mvaIdPhot_mc_Bkg_EE = new TH1F("mvaIdPhot_mc_Bkg_EE","mvaIdPhot_mc_Bkg_EE",100,-1,1);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(88,160.9293);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(89,515.5101);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(90,518.4368);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(91,618.8285);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(92,659.4706);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(93,768.2411);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(94,841.6568);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(95,601.6913);
   mvaIdPhot_mc_Bkg_EE->SetBinError(88,8.134656);
   mvaIdPhot_mc_Bkg_EE->SetBinError(89,14.70753);
   mvaIdPhot_mc_Bkg_EE->SetBinError(90,14.74784);
   mvaIdPhot_mc_Bkg_EE->SetBinError(91,16.13517);
   mvaIdPhot_mc_Bkg_EE->SetBinError(92,16.56507);
   mvaIdPhot_mc_Bkg_EE->SetBinError(93,17.96729);
   mvaIdPhot_mc_Bkg_EE->SetBinError(94,18.79703);
   mvaIdPhot_mc_Bkg_EE->SetBinError(95,15.96196);
   mvaIdPhot_mc_Bkg_EE->SetEntries(31070);
   mvaIdPhot_mc_Bkg_EE->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetLineColor(ci);
   mvaIdPhot_mc_Bkg_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Bkg_EE,"");
   
   TH1F *mvaIdPhot_mc_Signal_EE = new TH1F("mvaIdPhot_mc_Signal_EE","mvaIdPhot_mc_Signal_EE",100,-1,1);
   mvaIdPhot_mc_Signal_EE->SetBinContent(88,27.85573);
   mvaIdPhot_mc_Signal_EE->SetBinContent(89,106.7053);
   mvaIdPhot_mc_Signal_EE->SetBinContent(90,120.0365);
   mvaIdPhot_mc_Signal_EE->SetBinContent(91,164.5514);
   mvaIdPhot_mc_Signal_EE->SetBinContent(92,204.3774);
   mvaIdPhot_mc_Signal_EE->SetBinContent(93,266.1695);
   mvaIdPhot_mc_Signal_EE->SetBinContent(94,346.7452);
   mvaIdPhot_mc_Signal_EE->SetBinContent(95,275.7455);
   mvaIdPhot_mc_Signal_EE->SetBinError(88,1.835233);
   mvaIdPhot_mc_Signal_EE->SetBinError(89,4.338603);
   mvaIdPhot_mc_Signal_EE->SetBinError(90,4.359979);
   mvaIdPhot_mc_Signal_EE->SetBinError(91,5.504008);
   mvaIdPhot_mc_Signal_EE->SetBinError(92,5.903773);
   mvaIdPhot_mc_Signal_EE->SetBinError(93,6.848312);
   mvaIdPhot_mc_Signal_EE->SetBinError(94,7.637554);
   mvaIdPhot_mc_Signal_EE->SetBinError(95,6.806174);
   mvaIdPhot_mc_Signal_EE->SetEntries(62514);
   mvaIdPhot_mc_Signal_EE->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetLineColor(ci);
   mvaIdPhot_mc_Signal_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Signal_EE,"");
   ->Draw("hsame");
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(88,217);
   mvaIdPhot_data_EE->SetBinContent(89,608);
   mvaIdPhot_data_EE->SetBinContent(90,640);
   mvaIdPhot_data_EE->SetBinContent(91,769);
   mvaIdPhot_data_EE->SetBinContent(92,889);
   mvaIdPhot_data_EE->SetBinContent(93,1030);
   mvaIdPhot_data_EE->SetBinContent(94,1191);
   mvaIdPhot_data_EE->SetBinContent(95,872);
   mvaIdPhot_data_EE->SetBinError(88,14.73092);
   mvaIdPhot_data_EE->SetBinError(89,24.65766);
   mvaIdPhot_data_EE->SetBinError(90,25.29822);
   mvaIdPhot_data_EE->SetBinError(91,27.73085);
   mvaIdPhot_data_EE->SetBinError(92,29.8161);
   mvaIdPhot_data_EE->SetBinError(93,32.09361);
   mvaIdPhot_data_EE->SetBinError(94,34.51087);
   mvaIdPhot_data_EE->SetBinError(95,29.52965);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(1667.4);
   mvaIdPhot_data_EE->SetEntries(6216);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PESAME");
   
   TLegend *leg = new TLegend(0,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EE","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("mvaIdPhot_data_EE","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Bkg_EE","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Signal_EE","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   mvaIdPhot->Modified();
   mvaIdPhot->cd();
   mvaIdPhot->SetSelected(mvaIdPhot);
}
