/********************************************************************
* /cmshome/gdimperi/GammaJet/GammaJetAnalysis/CMSSW_5_3_11/src/GammaJets/macros/calculate_rhoWeights_data_C_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /cmshome/gdimperi/GammaJet/GammaJetAnalysis/CMSSW_5_3_11/src/GammaJets/macros/calculate_rhoWeights_data_C_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecalculate_rhoWeights_data_C_ACLiC_dict();
extern void G__cpp_setup_inheritancecalculate_rhoWeights_data_C_ACLiC_dict();
extern void G__cpp_setup_typetablecalculate_rhoWeights_data_C_ACLiC_dict();
extern void G__cpp_setup_memvarcalculate_rhoWeights_data_C_ACLiC_dict();
extern void G__cpp_setup_globalcalculate_rhoWeights_data_C_ACLiC_dict();
extern void G__cpp_setup_memfunccalculate_rhoWeights_data_C_ACLiC_dict();
extern void G__cpp_setup_funccalculate_rhoWeights_data_C_ACLiC_dict();
extern void G__set_cpp_environmentcalculate_rhoWeights_data_C_ACLiC_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/cmshome/gdimperi/GammaJet/GammaJetAnalysis/CMSSW_5_3_11/src/GammaJets/macros/./calculate_rhoWeights_data.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__calculate_rhoWeights_data_C_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;

/* STUB derived class for protected member access */
