{
//=========Macro generated from canvas: mvaIdPhot/mvaIdPhot
//=========  (Tue Feb 18 13:00:37 2014) by ROOT version5.32/00
   TCanvas *mvaIdPhot = new TCanvas("mvaIdPhot", "mvaIdPhot",0,0,1000,900);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   mvaIdPhot->SetHighLightColor(2);
   mvaIdPhot->Range(0,0,1,1);
   mvaIdPhot->SetFillColor(0);
   mvaIdPhot->SetBorderMode(0);
   mvaIdPhot->SetBorderSize(2);
   mvaIdPhot->SetTickx(1);
   mvaIdPhot->SetLeftMargin(0.13);
   mvaIdPhot->SetRightMargin(0.07);
   mvaIdPhot->SetFrameFillStyle(0);
   mvaIdPhot->SetFrameBorderMode(0);
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(94,376);
   mvaIdPhot_data_EE->SetBinContent(95,1395);
   mvaIdPhot_data_EE->SetBinContent(96,1920);
   mvaIdPhot_data_EE->SetBinContent(97,2525);
   mvaIdPhot_data_EE->SetBinContent(98,3862);
   mvaIdPhot_data_EE->SetBinContent(99,3372);
   mvaIdPhot_data_EE->SetBinContent(100,449);
   mvaIdPhot_data_EE->SetBinError(94,19.39072);
   mvaIdPhot_data_EE->SetBinError(95,37.3497);
   mvaIdPhot_data_EE->SetBinError(96,43.8178);
   mvaIdPhot_data_EE->SetBinError(97,50.24938);
   mvaIdPhot_data_EE->SetBinError(98,62.14499);
   mvaIdPhot_data_EE->SetBinError(99,58.06892);
   mvaIdPhot_data_EE->SetBinError(100,21.18962);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(5406.8);
   mvaIdPhot_data_EE->SetEntries(13899);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *mvaIdPhot_mc_Bkg_EE = new TH1F("mvaIdPhot_mc_Bkg_EE","mvaIdPhot_mc_Bkg_EE",100,-1,1);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(94,272.0519);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(95,862.1212);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(96,907.2887);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(97,1039.419);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(98,1034.047);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(99,480.3703);
   mvaIdPhot_mc_Bkg_EE->SetBinContent(100,27.60174);
   mvaIdPhot_mc_Bkg_EE->SetBinError(94,24.65824);
   mvaIdPhot_mc_Bkg_EE->SetBinError(95,43.04519);
   mvaIdPhot_mc_Bkg_EE->SetBinError(96,42.0126);
   mvaIdPhot_mc_Bkg_EE->SetBinError(97,45.79712);
   mvaIdPhot_mc_Bkg_EE->SetBinError(98,45.68771);
   mvaIdPhot_mc_Bkg_EE->SetBinError(99,30.44709);
   mvaIdPhot_mc_Bkg_EE->SetBinError(100,7.802033);
   mvaIdPhot_mc_Bkg_EE->SetEntries(29379);
   mvaIdPhot_mc_Bkg_EE->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   mvaIdPhot_mc_Bkg_EE->SetLineColor(ci);
   mvaIdPhot_mc_Bkg_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Bkg_EE,"");
   
   TH1F *mvaIdPhot_mc_Signal_EE = new TH1F("mvaIdPhot_mc_Signal_EE","mvaIdPhot_mc_Signal_EE",100,-1,1);
   mvaIdPhot_mc_Signal_EE->SetBinContent(94,130.9011);
   mvaIdPhot_mc_Signal_EE->SetBinContent(95,574.8531);
   mvaIdPhot_mc_Signal_EE->SetBinContent(96,941.2635);
   mvaIdPhot_mc_Signal_EE->SetBinContent(97,1472.456);
   mvaIdPhot_mc_Signal_EE->SetBinContent(98,2511.806);
   mvaIdPhot_mc_Signal_EE->SetBinContent(99,2778.921);
   mvaIdPhot_mc_Signal_EE->SetBinContent(100,181.2682);
   mvaIdPhot_mc_Signal_EE->SetBinError(94,8.612824);
   mvaIdPhot_mc_Signal_EE->SetBinError(95,16.31806);
   mvaIdPhot_mc_Signal_EE->SetBinError(96,22.66714);
   mvaIdPhot_mc_Signal_EE->SetBinError(97,24.58397);
   mvaIdPhot_mc_Signal_EE->SetBinError(98,29.32126);
   mvaIdPhot_mc_Signal_EE->SetBinError(99,33.34736);
   mvaIdPhot_mc_Signal_EE->SetBinError(100,4.930671);
   mvaIdPhot_mc_Signal_EE->SetEntries(353605);
   mvaIdPhot_mc_Signal_EE->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   mvaIdPhot_mc_Signal_EE->SetLineColor(ci);
   mvaIdPhot_mc_Signal_EE->SetLineWidth(2);
   ->Add(mvaIdPhot_mc_Signal_EE,"");
   ->Draw("hsame");
   
   TH1F *mvaIdPhot_data_EE = new TH1F("mvaIdPhot_data_EE","mvaIdPhot_data_EE",100,-1,1);
   mvaIdPhot_data_EE->SetBinContent(94,376);
   mvaIdPhot_data_EE->SetBinContent(95,1395);
   mvaIdPhot_data_EE->SetBinContent(96,1920);
   mvaIdPhot_data_EE->SetBinContent(97,2525);
   mvaIdPhot_data_EE->SetBinContent(98,3862);
   mvaIdPhot_data_EE->SetBinContent(99,3372);
   mvaIdPhot_data_EE->SetBinContent(100,449);
   mvaIdPhot_data_EE->SetBinError(94,19.39072);
   mvaIdPhot_data_EE->SetBinError(95,37.3497);
   mvaIdPhot_data_EE->SetBinError(96,43.8178);
   mvaIdPhot_data_EE->SetBinError(97,50.24938);
   mvaIdPhot_data_EE->SetBinError(98,62.14499);
   mvaIdPhot_data_EE->SetBinError(99,58.06892);
   mvaIdPhot_data_EE->SetBinError(100,21.18962);
   mvaIdPhot_data_EE->SetMinimum(0);
   mvaIdPhot_data_EE->SetMaximum(5406.8);
   mvaIdPhot_data_EE->SetEntries(13899);
   mvaIdPhot_data_EE->SetStats(0);
   mvaIdPhot_data_EE->SetMarkerStyle(20);
   mvaIdPhot_data_EE->SetMarkerSize(0.7);
   mvaIdPhot_data_EE->GetXaxis()->SetTitle("#gamma MVA output");
   mvaIdPhot_data_EE->GetYaxis()->SetTitle("Entries/0.02");
   mvaIdPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   mvaIdPhot_data_EE->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.086773e-312,1.086773e-312,2.329657e-310,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EE","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("mvaIdPhot_data_EE","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Bkg_EE","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mvaIdPhot_mc_Signal_EE","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   mvaIdPhot->Modified();
   mvaIdPhot->cd();
   mvaIdPhot->SetSelected(mvaIdPhot);
}
