{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Fri Jan 31 17:02:23 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",1,1,1000,876);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(-48.75,-6585.359,326.25,59268.22);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(9,8955);
   ptPhot_data_EB->SetBinContent(10,5179);
   ptPhot_data_EB->SetBinContent(11,3258);
   ptPhot_data_EB->SetBinContent(12,2049);
   ptPhot_data_EB->SetBinContent(13,1408);
   ptPhot_data_EB->SetBinError(9,94.63086);
   ptPhot_data_EB->SetBinError(10,71.96527);
   ptPhot_data_EB->SetBinError(11,57.07889);
   ptPhot_data_EB->SetBinError(12,45.26588);
   ptPhot_data_EB->SetBinError(13,37.52333);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(12537);
   ptPhot_data_EB->SetEntries(20849);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_EB = new TH1F("ptPhot_mc_Bkg_EB","ptPhot_mc_Bkg_EB",60,0,300);
   ptPhot_mc_Bkg_EB->SetBinContent(9,4139.257);
   ptPhot_mc_Bkg_EB->SetBinContent(10,2232.262);
   ptPhot_mc_Bkg_EB->SetBinContent(11,1222.499);
   ptPhot_mc_Bkg_EB->SetBinContent(12,739.1053);
   ptPhot_mc_Bkg_EB->SetBinContent(13,440.4574);
   ptPhot_mc_Bkg_EB->SetBinError(9,41.89021);
   ptPhot_mc_Bkg_EB->SetBinError(10,30.81522);
   ptPhot_mc_Bkg_EB->SetBinError(11,22.63415);
   ptPhot_mc_Bkg_EB->SetBinError(12,17.40142);
   ptPhot_mc_Bkg_EB->SetBinError(13,12.99805);
   ptPhot_mc_Bkg_EB->SetEntries(79278);
   ptPhot_mc_Bkg_EB->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EB->SetLineColor(ci);
   ptPhot_mc_Bkg_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_EB,"");
   
   TH1F *ptPhot_mc_Signal_EB = new TH1F("ptPhot_mc_Signal_EB","ptPhot_mc_Signal_EB",60,0,300);
   ptPhot_mc_Signal_EB->SetBinContent(9,4739.042);
   ptPhot_mc_Signal_EB->SetBinContent(10,2991.407);
   ptPhot_mc_Signal_EB->SetBinContent(11,1943.879);
   ptPhot_mc_Signal_EB->SetBinContent(12,1285.002);
   ptPhot_mc_Signal_EB->SetBinContent(13,890.6265);
   ptPhot_mc_Signal_EB->SetBinError(9,27.18203);
   ptPhot_mc_Signal_EB->SetBinError(10,19.95391);
   ptPhot_mc_Signal_EB->SetBinError(11,14.75798);
   ptPhot_mc_Signal_EB->SetBinError(12,10.68676);
   ptPhot_mc_Signal_EB->SetBinError(13,8.222157);
   ptPhot_mc_Signal_EB->SetEntries(933061);
   ptPhot_mc_Signal_EB->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EB->SetLineColor(ci);
   ptPhot_mc_Signal_EB->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_EB,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_EB = new TH1F("ptPhot_data_EB","ptPhot_data_EB",60,0,300);
   ptPhot_data_EB->SetBinContent(9,8955);
   ptPhot_data_EB->SetBinContent(10,5179);
   ptPhot_data_EB->SetBinContent(11,3258);
   ptPhot_data_EB->SetBinContent(12,2049);
   ptPhot_data_EB->SetBinContent(13,1408);
   ptPhot_data_EB->SetBinError(9,94.63086);
   ptPhot_data_EB->SetBinError(10,71.96527);
   ptPhot_data_EB->SetBinError(11,57.07889);
   ptPhot_data_EB->SetBinError(12,45.26588);
   ptPhot_data_EB->SetBinError(13,37.52333);
   ptPhot_data_EB->SetMinimum(0);
   ptPhot_data_EB->SetMaximum(12537);
   ptPhot_data_EB->SetEntries(20849);
   ptPhot_data_EB->SetStats(0);
   ptPhot_data_EB->SetMarkerStyle(20);
   ptPhot_data_EB->SetMarkerSize(0.7);
   ptPhot_data_EB->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EB->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EB->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EB->Draw("PESAME");
   
   TLegend *leg = new TLegend(1.411912e-309,3.237958e-319,2.357743e-310,0,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EB","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_EB","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_EB","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_EB","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
