{
//=========Macro generated from canvas: ptPhot/ptPhot
//=========  (Fri Jan 31 17:02:18 2014) by ROOT version5.32/00
   TCanvas *ptPhot = new TCanvas("ptPhot", "ptPhot",0,0,1000,900);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   ptPhot->SetHighLightColor(2);
   ptPhot->Range(0,0,1,1);
   ptPhot->SetFillColor(0);
   ptPhot->SetBorderMode(0);
   ptPhot->SetBorderSize(2);
   ptPhot->SetTickx(1);
   ptPhot->SetLeftMargin(0.13);
   ptPhot->SetRightMargin(0.07);
   ptPhot->SetFrameFillStyle(0);
   ptPhot->SetFrameBorderMode(0);
   
   TH1F *ptPhot_data_EE = new TH1F("ptPhot_data_EE","ptPhot_data_EE",60,0,300);
   ptPhot_data_EE->SetBinContent(9,7987);
   ptPhot_data_EE->SetBinContent(10,4825);
   ptPhot_data_EE->SetBinContent(11,3005);
   ptPhot_data_EE->SetBinContent(12,1898);
   ptPhot_data_EE->SetBinContent(13,1226);
   ptPhot_data_EE->SetBinError(9,89.37002);
   ptPhot_data_EE->SetBinError(10,69.46222);
   ptPhot_data_EE->SetBinError(11,54.81788);
   ptPhot_data_EE->SetBinError(12,43.56604);
   ptPhot_data_EE->SetBinError(13,35.01428);
   ptPhot_data_EE->SetMinimum(0);
   ptPhot_data_EE->SetMaximum(11181.8);
   ptPhot_data_EE->SetEntries(18941);
   ptPhot_data_EE->SetStats(0);
   ptPhot_data_EE->SetMarkerStyle(20);
   ptPhot_data_EE->SetMarkerSize(0.7);
   ptPhot_data_EE->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EE->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EE->Draw("PE");
   
   THStack * = new THStack();
   ->SetName("");
   ->SetTitle("");
   
   TH1F *ptPhot_mc_Bkg_EE = new TH1F("ptPhot_mc_Bkg_EE","ptPhot_mc_Bkg_EE",60,0,300);
   ptPhot_mc_Bkg_EE->SetBinContent(9,4760.086);
   ptPhot_mc_Bkg_EE->SetBinContent(10,2600.912);
   ptPhot_mc_Bkg_EE->SetBinContent(11,1521.594);
   ptPhot_mc_Bkg_EE->SetBinContent(12,916.5459);
   ptPhot_mc_Bkg_EE->SetBinContent(13,574.2922);
   ptPhot_mc_Bkg_EE->SetBinError(9,44.9905);
   ptPhot_mc_Bkg_EE->SetBinError(10,33.39207);
   ptPhot_mc_Bkg_EE->SetBinError(11,25.39274);
   ptPhot_mc_Bkg_EE->SetBinError(12,19.4689);
   ptPhot_mc_Bkg_EE->SetBinError(13,14.98641);
   ptPhot_mc_Bkg_EE->SetEntries(64136);
   ptPhot_mc_Bkg_EE->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EE->SetFillColor(ci);

   ci = TColor::GetColor("#ff00ff");
   ptPhot_mc_Bkg_EE->SetLineColor(ci);
   ptPhot_mc_Bkg_EE->SetLineWidth(2);
   ->Add(ptPhot_mc_Bkg_EE,"");
   
   TH1F *ptPhot_mc_Signal_EE = new TH1F("ptPhot_mc_Signal_EE","ptPhot_mc_Signal_EE",60,0,300);
   ptPhot_mc_Signal_EE->SetBinContent(9,3456.631);
   ptPhot_mc_Signal_EE->SetBinContent(10,2121.269);
   ptPhot_mc_Signal_EE->SetBinContent(11,1355.41);
   ptPhot_mc_Signal_EE->SetBinContent(12,903.968);
   ptPhot_mc_Signal_EE->SetBinContent(13,626.8545);
   ptPhot_mc_Signal_EE->SetBinError(9,24.31569);
   ptPhot_mc_Signal_EE->SetBinError(10,17.53411);
   ptPhot_mc_Signal_EE->SetBinError(11,12.7299);
   ptPhot_mc_Signal_EE->SetBinError(12,9.476752);
   ptPhot_mc_Signal_EE->SetBinError(13,7.345342);
   ptPhot_mc_Signal_EE->SetEntries(601872);
   ptPhot_mc_Signal_EE->SetStats(0);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EE->SetFillColor(ci);

   ci = TColor::GetColor("#00ffff");
   ptPhot_mc_Signal_EE->SetLineColor(ci);
   ptPhot_mc_Signal_EE->SetLineWidth(2);
   ->Add(ptPhot_mc_Signal_EE,"");
   ->Draw("hsame");
   
   TH1F *ptPhot_data_EE = new TH1F("ptPhot_data_EE","ptPhot_data_EE",60,0,300);
   ptPhot_data_EE->SetBinContent(9,7987);
   ptPhot_data_EE->SetBinContent(10,4825);
   ptPhot_data_EE->SetBinContent(11,3005);
   ptPhot_data_EE->SetBinContent(12,1898);
   ptPhot_data_EE->SetBinContent(13,1226);
   ptPhot_data_EE->SetBinError(9,89.37002);
   ptPhot_data_EE->SetBinError(10,69.46222);
   ptPhot_data_EE->SetBinError(11,54.81788);
   ptPhot_data_EE->SetBinError(12,43.56604);
   ptPhot_data_EE->SetBinError(13,35.01428);
   ptPhot_data_EE->SetMinimum(0);
   ptPhot_data_EE->SetMaximum(11181.8);
   ptPhot_data_EE->SetEntries(18941);
   ptPhot_data_EE->SetStats(0);
   ptPhot_data_EE->SetMarkerStyle(20);
   ptPhot_data_EE->SetMarkerSize(0.7);
   ptPhot_data_EE->GetXaxis()->SetTitle("#gamma p_{T} (GeV)");
   ptPhot_data_EE->GetYaxis()->SetTitle("Entries/5.0");
   ptPhot_data_EE->GetYaxis()->SetTitleOffset(1.5);
   ptPhot_data_EE->Draw("PESAME");
   
   TLegend *leg = new TLegend(3.506354e+151,3.680699e+180,1.465158e+117,1.809515e-319,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.038);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","EE","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("ptPhot_data_EE","Data","PL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Bkg_EE","Bkg","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("ptPhot_mc_Signal_EE","Signal","F");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.25,0.94,"CMS Preliminary #sqrt{s}=8 TeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextSize(0.037);
   tex->SetLineWidth(2);
   tex->Draw();
   ptPhot->Modified();
   ptPhot->cd();
   ptPhot->SetSelected(ptPhot);
}
